[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-model-versions"
version = "0.1.0"
description = "A robust, elegant and efficient Django model versioning package."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "Joaquín Vázquez", email = "jota.dev.es@gmail.com"},
]
dependencies = [
  "Django>=4.2",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-django",
  "psycopg2-binary",
]

[tool.hatch.build.targets.wheel]
packages = ["django_model_versions"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
pythonpath = "."
python_files = ["test_*.py", "*_test.py"]
